const actions = {
  SET_ACTIVE_CATEGORY: 'SET_ACTIVE_CATEGORY',
  GET_RECIPES_BY_CATEGORY: 'GET_RECIPES_BY_CATEGORY',
  GET_RECIPES_BY_CATEGORY_SUCCESS: 'GET_RECIPES_BY_CATEGORY_SUCCESS',
  GET_RECIPES_BY_CATEGORY_ERROR: 'GET_RECIPES_BY_CATEGORY_ERROR',

  GET_NEXT_RECIPES_BY_CATEGORY: 'GET_NEXT_RECIPES_BY_CATEGORY',
  GET_NEXT_RECIPES_BY_CATEGORY_SUCCESS: 'GET_NEXT_RECIPES_BY_CATEGORY_SUCCESS',
  GET_NEXT_RECIPES_BY_CATEGORY_ERROR: 'GET_NEXT_RECIPES_BY_CATEGORY_ERROR',

  GET_RECIPES_BY_SEARCH: 'GET_RECIPES_BY_SEARCH',
  GET_RECIPES_BY_SEARCH_SUCCESS: 'GET_RECIPES_BY_SEARCH_SUCCESS',
  GET_RECIPES_BY_SEARCH_ERROR: 'GET_RECIPES_BY_SEARCH_ERROR',

  GET_NEXT_RECIPES_BY_SEARCH: 'GET_NEXT_RECIPES_BY_SEARCH',
  GET_NEXT_RECIPES_BY_SEARCH_SUCCESS: 'GET_NEXT_RECIPES_BY_SEARCH_SUCCESS',
  GET_NEXT_RECIPES_BY_SEARCH_ERROR: 'GET_NEXT_RECIPES_BY_SEARCH_ERROR',
};

export default actions;
