const actions = {
  GET_RECIPE_INFORMATION_BY_ID: 'GET_RECIPE_INFORMATION_BY_ID',
  GET_RECIPE_INFORMATION_BY_ID_SUCCESS: 'GET_RECIPE_INFORMATION_BY_ID_SUCCESS',
  GET_RECIPE_INFORMATION_BY_ID_ERROR: 'GET_RECIPE_INFORMATION_BY_ID_ERROR',
}

export default actions