const actions = {
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  GET_SEARCH_AUTOCOMPLETE: 'GET_SEARCH_AUTOCOMPLETE',
  GET_SEARCH_AUTOCOMPLETE_SUCCESS: 'GET_SEARCH_AUTOCOMPLETE_SUCCESS',
  GET_SEARCH_AUTOCOMPLETE_ERROR: 'GET_SEARCH_AUTOCOMPLETE_ERROR',
};

export default actions;
